// angular-poke/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'header-comp',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<header>
  <a href="http://localhost:3000/">
    <img src="favicon.ico" alt="switch to React" />
  </a>
  <nav>
    <a routerLink="/"><h1>pokedex</h1></a>
  </nav>
</header>

// react-poke-ts/src/components/Header.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';

const Header = () => {
  return (
    <header>
      <a href="http://localhost:4200/" title="switch to Angular">
        <img alt="react" src={'/logo192.png'} />
      </a>
      <NavLink to="/">
        <h1>Pokedex</h1>
      </NavLink>
    </header>
  );
};

export default Header;
