// angular-poke/src/app/card/card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { PokemonService } from '../helpers/pokemon.service';

import { PokemonDetails, Pokemon } from '../helpers/interfaces';

@Component({
  selector: 'card-comp',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent implements OnInit {

  @Input() cardPokemon: Pokemon = {
    name: '',
    url: ''
  };

  pokemon!: PokemonDetails;
  pokeImg!: string;

  onImgError(e: Event){
    const target = e.target as HTMLImageElement;
    target.src = this.pokemon.sprites.front_default
   }

  constructor(
    private pokemonService: PokemonService,
  ) {}

  ngOnInit(): void {
    this.getPokemon();
  }

  getPokemon(): void {
    this.pokemonService.getPokemon(this.cardPokemon.name)
      .subscribe(pokemon => {
        this.pokemon = pokemon
        this.pokeImg =  this.pokemonService.getPokemonImage(pokemon.id.toString().padStart(3, "0"))
      })
  }


}

<loader-comp *ngIf="!pokemon"></loader-comp>

<div *ngIf="pokemon" class="{{'card backdrop-' + pokemon.types[0].type.name}}">
  <h2>{{ cardPokemon.name }}</h2>
  <img
    alt="{{pokemon.name}}"
    title="{{pokemon.name}}"
    src="{{ pokeImg }}"
    class="{{'anim backdrop-' + pokemon.types[0].type.name}}"
    (error)="onImgError($event)"
  />
  <div class="uni-row">
      <div *ngFor="let type of pokemon.types">
        <p class="{{'bg-' + type.type.name}}">{{type.type.name}}</p>
      </div>
  </div>
</div>

// react-poke/src/components/Card.jsx
import React, { useEffect, useState } from "react";

import { fetchApi, GetImageById } from '../services/api'

import Loader from './Loader';

const Card = (props) => {

  const [pokemon, setPokemon] = useState(null);

  useEffect(() => {
    if (props.pokemon) {
      fetchApi(`pokemon/${props.pokemon.name}`, setPokemon);
    }
  }, [props.pokemon])

  return (
    (!pokemon ?
      <Loader /> :
      <div className={`card backdrop-${pokemon.types[0].type.name}`}>
        <h2>{pokemon.name}</h2>
        <img
          alt={pokemon.name}
          title={pokemon.name}
          src={GetImageById(pokemon.id)}
          className={"anim"}
          onError={(e) =>
            (e.target.onerror = null)(
              (e.target.src = pokemon.sprites.front_default)
            )
          }
        />
        <div className="uni-row">
          {pokemon.types.map(type =>
            <div key={type.type.name}>
              <p className={`bg-${type.type.name}`}>{type.type.name}</p>
            </div>
          )}
        </div>
      </div>
    )
  );
}

export default Card;
