// react-poke-ts/src/components/Details.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

import { fetchApi, GetImageById } from '../services/api';

import Loader from './Loader';
import { Pokemon } from '../types';

const Details = () => {
  const [pokemon, setPokemon] = useState<Pokemon | null>(null);
  const { name } = useParams();

  useEffect(() => {
    fetchApi(`pokemon/${name}`, setPokemon);
  }, [name]);

  const onImgError = (error) => {
    const sprite = pokemon?.sprites.front_default;
    const pokeBall =
      'https://upload.wikimedia.org/wikipedia/commons/5/53/Pok%C3%A9_Ball_icon.svg';
    error.target.src = sprite ? sprite : pokeBall;
  };

  return !pokemon ? (
    <Loader />
  ) : (
    <div className="container details">
      <div className="row">
        <div className="col-md-6 col-sm-12 col-xs-12">
          <div className={`card base backdrop-${pokemon.types[0].type.name}`}>
            <h2 className={`backdrop-${pokemon.types[0].type.name}`}>
              {pokemon.name}
            </h2>
            <img
              alt={pokemon.name}
              title={pokemon.name}
              src={GetImageById(pokemon.id)}
              className="anim"
              onError={onImgError}
            />
            <div className="uni-row">
              {pokemon.types.map((type) => (
                <div key={type.type.name}>
                  <p className={`bg-${type.type.name}`}>{type.type.name}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
        <div className="col-md-6 col-sm-12 col-xs-12">
          <div className="card row">
            <h2 className="col-md-12">Base Info</h2>
            <div className="item col-md-6 col-sm-12 col-xs-12">
              <p>Height: </p>
              <span>{Math.round(pokemon.height * 10) / 100} m</span>
            </div>
            <div className="item col-md-6 col-sm-12 col-xs-12">
              <p>Weight: </p>
              <span>{Math.round(pokemon.weight * 10) / 100} kg</span>
            </div>
            <div className="item col-md-6 col-sm-12 col-xs-12">
              <p>Abilities: </p>
              <ul>
                {pokemon.abilities.map((ability) => (
                  <li key={ability.ability.name}>{ability.ability.name}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className="row stat">
        <div className="col-md-12 col-sm-12 col-xs-12">
          <div className="card">
            <h2>Stats</h2>
            <div className="row">
              {pokemon.stats.map((stat) => (
                <div className="col-md-2 col-sm-4 col-xs-6" key={stat.stat.url}>
                  <div className="bar">
                    <div
                      style={{ height: stat.base_stat }}
                      className={`bar-active bg-${pokemon.types[0].type.name}`}
                    />
                    <span className="value">{stat.base_stat}</span>
                  </div>
                  <p>{stat.stat.name}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Details;

// angular-poke/src/app/details/details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';

import { PokemonDetails } from '../helpers/interfaces';
import { PokemonService } from '../helpers/pokemon.service';

@Component({
  selector: 'details-comp',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.scss']
})
export class DetailsComponent implements OnInit {
  pokemon!: PokemonDetails;
  pokeImg!: string;

  height!: number;
  weight!: number;

  onImgError(e: Event) {
    const target = e.target as HTMLImageElement;
    const sprite = this.pokemon.sprites.front_default
    const pokeBall = 'https://upload.wikimedia.org/wikipedia/commons/5/53/Pok%C3%A9_Ball_icon.svg';
    target.src = sprite ? sprite : pokeBall
  }

  constructor(
    private route: ActivatedRoute,
    private pokemonService: PokemonService,
    private location: Location
  ) { }

  ngOnInit(): void {
    this.getPokemon();
  }

  getPokemon(): void {
    const name = this.route.snapshot.paramMap.get('name')!;
    this.pokemonService.getPokemon(name)
      .subscribe(pokemon => {
        this.pokemon = pokemon
        this.pokeImg = this.pokemonService.getPokemonImage(pokemon.id.toString().padStart(3, "0"))
        this.height = Math.round(pokemon.height * 10) / 100;
        this.weight = Math.round(pokemon.weight * 10) / 100;
      })
  }
}

<loader-comp *ngIf="!pokemon"></loader-comp>

<div *ngIf="pokemon" class="container details">
  <div class="row">
    <div class="col-md-6">
      <div class="{{ 'card base backdrop' + pokemon.types[0].type.name }}">
        <h2 class="{{ 'backdrop-' + pokemon.types[0].type.name }}">
          {{ pokemon.name }}
        </h2>
        <img
          alt="{{ pokemon.name }}"
          title="{{ pokemon.name }}"
          src="{{ pokeImg }}"
          class="anim"
          (error)="onImgError($event)"
        />
        <div class="uni-row">
          <div *ngFor="let type of pokemon.types">
            <p class="{{ 'bg-' + type.type.name }}">{{ type.type.name }}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card row">
        <h2 class="col-md-12">Base Info</h2>
        <div class="item col-md-6">
          <p>Height:</p>
          <span> {{ height }} m </span>
        </div>
        <div class="item col-md-6">
          <p>Weight:</p>
          <span> {{ weight }} kg </span>
        </div>
        <div class="item col-md-6">
          <p>Abilities:</p>
          <ul>
            <li *ngFor="let detail of pokemon.abilities">
              {{ detail.ability.name }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row stat">
    <div class="col-md-12">
      <div class="card">
        <h2>Stats</h2>
        <div class="row">
          <div *ngFor="let stat of pokemon.stats" class="col-md-2">
            <div class="bar">
              <div
                [ngStyle]="{ 'height.px': stat.base_stat }"
                class="{{ 'bar-active bg-' + pokemon.types[0].type.name }}"
              ></div>
              <p class="value">{{ stat.base_stat }}</p>
            </div>
            <p>
              {{ stat.stat.name }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
